# Generated by Django 2.1.7 on 2019-04-17 09:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('popularity', models.FloatField(blank=True)),
                ('director', models.TextField(blank=True)),
                ('genre', models.TextField(blank=True)),
                ('imdb_score', models.FloatField(blank=True)),
                ('name', models.CharField(max_length=255)),
                ('cover', models.FileField(blank=True, upload_to='movie_cover_photo')),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
